//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class CigiWeatherCtrlV3 : CigiBaseWeatherCtrl {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal CigiWeatherCtrlV3(global::System.IntPtr cPtr, bool cMemoryOwn) : base(example_modulePINVOKE.CigiWeatherCtrlV3_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CigiWeatherCtrlV3 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CigiWeatherCtrlV3 obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          example_modulePINVOKE.delete_CigiWeatherCtrlV3(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public CigiWeatherCtrlV3() : this(example_modulePINVOKE.new_CigiWeatherCtrlV3(), true) {
  }

  public override int Pack(CigiBasePacket Base, SWIGTYPE_p_unsigned___int8 Buff, SWIGTYPE_p_void Spec) {
    int ret = example_modulePINVOKE.CigiWeatherCtrlV3_Pack(swigCPtr, CigiBasePacket.getCPtr(Base), SWIGTYPE_p_unsigned___int8.getCPtr(Buff), SWIGTYPE_p_void.getCPtr(Spec));
    return ret;
  }

  public override int Unpack(SWIGTYPE_p_unsigned___int8 Buff, bool Swap, SWIGTYPE_p_void Spec) {
    int ret = example_modulePINVOKE.CigiWeatherCtrlV3_Unpack(swigCPtr, SWIGTYPE_p_unsigned___int8.getCPtr(Buff), Swap, SWIGTYPE_p_void.getCPtr(Spec));
    return ret;
  }

  public int SetRegionID(SWIGTYPE_p_unsigned___int16 RegionIDIn, bool bndchk) {
    int ret = example_modulePINVOKE.CigiWeatherCtrlV3_SetRegionID__SWIG_0(swigCPtr, SWIGTYPE_p_unsigned___int16.getCPtr(RegionIDIn), bndchk);
    if (example_modulePINVOKE.SWIGPendingException.Pending) throw example_modulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int SetRegionID(SWIGTYPE_p_unsigned___int16 RegionIDIn) {
    int ret = example_modulePINVOKE.CigiWeatherCtrlV3_SetRegionID__SWIG_1(swigCPtr, SWIGTYPE_p_unsigned___int16.getCPtr(RegionIDIn));
    if (example_modulePINVOKE.SWIGPendingException.Pending) throw example_modulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_unsigned___int16 GetRegionID() {
    SWIGTYPE_p_unsigned___int16 ret = new SWIGTYPE_p_unsigned___int16(example_modulePINVOKE.CigiWeatherCtrlV3_GetRegionID(swigCPtr), true);
    return ret;
  }

  public int SetLayerID(SWIGTYPE_p_unsigned___int8 LayerIDIn, bool bndchk) {
    int ret = example_modulePINVOKE.CigiWeatherCtrlV3_SetLayerID__SWIG_0(swigCPtr, SWIGTYPE_p_unsigned___int8.getCPtr(LayerIDIn), bndchk);
    if (example_modulePINVOKE.SWIGPendingException.Pending) throw example_modulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int SetLayerID(SWIGTYPE_p_unsigned___int8 LayerIDIn) {
    int ret = example_modulePINVOKE.CigiWeatherCtrlV3_SetLayerID__SWIG_1(swigCPtr, SWIGTYPE_p_unsigned___int8.getCPtr(LayerIDIn));
    if (example_modulePINVOKE.SWIGPendingException.Pending) throw example_modulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_unsigned___int8 GetLayerID() {
    SWIGTYPE_p_unsigned___int8 ret = new SWIGTYPE_p_unsigned___int8(example_modulePINVOKE.CigiWeatherCtrlV3_GetLayerID(swigCPtr), true);
    return ret;
  }

  public int SetHumidity(SWIGTYPE_p_unsigned___int8 HumidityIn, bool bndchk) {
    int ret = example_modulePINVOKE.CigiWeatherCtrlV3_SetHumidity__SWIG_0(swigCPtr, SWIGTYPE_p_unsigned___int8.getCPtr(HumidityIn), bndchk);
    if (example_modulePINVOKE.SWIGPendingException.Pending) throw example_modulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int SetHumidity(SWIGTYPE_p_unsigned___int8 HumidityIn) {
    int ret = example_modulePINVOKE.CigiWeatherCtrlV3_SetHumidity__SWIG_1(swigCPtr, SWIGTYPE_p_unsigned___int8.getCPtr(HumidityIn));
    if (example_modulePINVOKE.SWIGPendingException.Pending) throw example_modulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_unsigned___int8 GetHumidity() {
    SWIGTYPE_p_unsigned___int8 ret = new SWIGTYPE_p_unsigned___int8(example_modulePINVOKE.CigiWeatherCtrlV3_GetHumidity(swigCPtr), true);
    return ret;
  }

  public int SetRandomLightningEn(bool RandomLightningEnIn, bool bndchk) {
    int ret = example_modulePINVOKE.CigiWeatherCtrlV3_SetRandomLightningEn__SWIG_0(swigCPtr, RandomLightningEnIn, bndchk);
    return ret;
  }

  public int SetRandomLightningEn(bool RandomLightningEnIn) {
    int ret = example_modulePINVOKE.CigiWeatherCtrlV3_SetRandomLightningEn__SWIG_1(swigCPtr, RandomLightningEnIn);
    return ret;
  }

  public bool GetRandomLightningEn() {
    bool ret = example_modulePINVOKE.CigiWeatherCtrlV3_GetRandomLightningEn(swigCPtr);
    return ret;
  }

  public int SetCloudType(CigiBaseWeatherCtrl.CloudTypeGrp CloudTypeIn, bool bndchk) {
    int ret = example_modulePINVOKE.CigiWeatherCtrlV3_SetCloudType__SWIG_0(swigCPtr, (int)CloudTypeIn, bndchk);
    return ret;
  }

  public int SetCloudType(CigiBaseWeatherCtrl.CloudTypeGrp CloudTypeIn) {
    int ret = example_modulePINVOKE.CigiWeatherCtrlV3_SetCloudType__SWIG_1(swigCPtr, (int)CloudTypeIn);
    return ret;
  }

  public CigiBaseWeatherCtrl.CloudTypeGrp GetCloudType() {
    CigiBaseWeatherCtrl.CloudTypeGrp ret = (CigiBaseWeatherCtrl.CloudTypeGrp)example_modulePINVOKE.CigiWeatherCtrlV3_GetCloudType(swigCPtr);
    return ret;
  }

  public int SetScope(CigiBaseWeatherCtrl.ScopeGrp ScopeIn, bool bndchk) {
    int ret = example_modulePINVOKE.CigiWeatherCtrlV3_SetScope__SWIG_0(swigCPtr, (int)ScopeIn, bndchk);
    return ret;
  }

  public int SetScope(CigiBaseWeatherCtrl.ScopeGrp ScopeIn) {
    int ret = example_modulePINVOKE.CigiWeatherCtrlV3_SetScope__SWIG_1(swigCPtr, (int)ScopeIn);
    return ret;
  }

  public CigiBaseWeatherCtrl.ScopeGrp GetScope() {
    CigiBaseWeatherCtrl.ScopeGrp ret = (CigiBaseWeatherCtrl.ScopeGrp)example_modulePINVOKE.CigiWeatherCtrlV3_GetScope(swigCPtr);
    return ret;
  }

  public int SetVertWindSp(float VertWindSpIn, bool bndchk) {
    int ret = example_modulePINVOKE.CigiWeatherCtrlV3_SetVertWindSp__SWIG_0(swigCPtr, VertWindSpIn, bndchk);
    return ret;
  }

  public int SetVertWindSp(float VertWindSpIn) {
    int ret = example_modulePINVOKE.CigiWeatherCtrlV3_SetVertWindSp__SWIG_1(swigCPtr, VertWindSpIn);
    return ret;
  }

  public float GetVertWindSp() {
    float ret = example_modulePINVOKE.CigiWeatherCtrlV3_GetVertWindSp(swigCPtr);
    return ret;
  }

  public int SetWindDir(float WindDirIn, bool bndchk) {
    int ret = example_modulePINVOKE.CigiWeatherCtrlV3_SetWindDir__SWIG_0(swigCPtr, WindDirIn, bndchk);
    return ret;
  }

  public int SetWindDir(float WindDirIn) {
    int ret = example_modulePINVOKE.CigiWeatherCtrlV3_SetWindDir__SWIG_1(swigCPtr, WindDirIn);
    return ret;
  }

  public float GetWindDir() {
    float ret = example_modulePINVOKE.CigiWeatherCtrlV3_GetWindDir(swigCPtr);
    return ret;
  }

  public int SetBaroPress(float BaroPressIn, bool bndchk) {
    int ret = example_modulePINVOKE.CigiWeatherCtrlV3_SetBaroPress__SWIG_0(swigCPtr, BaroPressIn, bndchk);
    return ret;
  }

  public int SetBaroPress(float BaroPressIn) {
    int ret = example_modulePINVOKE.CigiWeatherCtrlV3_SetBaroPress__SWIG_1(swigCPtr, BaroPressIn);
    return ret;
  }

  public float GetBaroPress() {
    float ret = example_modulePINVOKE.CigiWeatherCtrlV3_GetBaroPress(swigCPtr);
    return ret;
  }

  public int SetAerosol(float AerosolIn, bool bndchk) {
    int ret = example_modulePINVOKE.CigiWeatherCtrlV3_SetAerosol__SWIG_0(swigCPtr, AerosolIn, bndchk);
    return ret;
  }

  public int SetAerosol(float AerosolIn) {
    int ret = example_modulePINVOKE.CigiWeatherCtrlV3_SetAerosol__SWIG_1(swigCPtr, AerosolIn);
    return ret;
  }

  public float GetAerosol() {
    float ret = example_modulePINVOKE.CigiWeatherCtrlV3_GetAerosol(swigCPtr);
    return ret;
  }

}
