//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class CigiSOFV4 : CigiBaseSOF {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal CigiSOFV4(global::System.IntPtr cPtr, bool cMemoryOwn) : base(ccl_dllDPINVOKE.CigiSOFV4_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CigiSOFV4 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CigiSOFV4 obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ccl_dllDPINVOKE.delete_CigiSOFV4(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public CigiSOFV4() : this(ccl_dllDPINVOKE.new_CigiSOFV4(), true) {
  }

  public override int Pack(CigiBasePacket Base, SWIGTYPE_p_unsigned___int8 Buff, SWIGTYPE_p_void Spec) {
    int ret = ccl_dllDPINVOKE.CigiSOFV4_Pack(swigCPtr, CigiBasePacket.getCPtr(Base), SWIGTYPE_p_unsigned___int8.getCPtr(Buff), SWIGTYPE_p_void.getCPtr(Spec));
    return ret;
  }

  public override int Unpack(SWIGTYPE_p_unsigned___int8 Buff, bool Swap, SWIGTYPE_p_void Spec) {
    int ret = ccl_dllDPINVOKE.CigiSOFV4_Unpack(swigCPtr, SWIGTYPE_p_unsigned___int8.getCPtr(Buff), Swap, SWIGTYPE_p_void.getCPtr(Spec));
    return ret;
  }

  public new SWIGTYPE_p_unsigned___int32 GetFrameCntr() {
    SWIGTYPE_p_unsigned___int32 ret = new SWIGTYPE_p_unsigned___int32(ccl_dllDPINVOKE.CigiSOFV4_GetFrameCntr(swigCPtr), true);
    return ret;
  }

  public new int SetFrameCntr(SWIGTYPE_p_unsigned___int32 FrameCntrIn, bool bndchk) {
    int ret = ccl_dllDPINVOKE.CigiSOFV4_SetFrameCntr__SWIG_0(swigCPtr, SWIGTYPE_p_unsigned___int32.getCPtr(FrameCntrIn), bndchk);
    if (ccl_dllDPINVOKE.SWIGPendingException.Pending) throw ccl_dllDPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public new int SetFrameCntr(SWIGTYPE_p_unsigned___int32 FrameCntrIn) {
    int ret = ccl_dllDPINVOKE.CigiSOFV4_SetFrameCntr__SWIG_1(swigCPtr, SWIGTYPE_p_unsigned___int32.getCPtr(FrameCntrIn));
    if (ccl_dllDPINVOKE.SWIGPendingException.Pending) throw ccl_dllDPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_unsigned___int32 GetTimeStamp() {
    SWIGTYPE_p_unsigned___int32 ret = new SWIGTYPE_p_unsigned___int32(ccl_dllDPINVOKE.CigiSOFV4_GetTimeStamp(swigCPtr), true);
    return ret;
  }

  public int SetTimeStamp(SWIGTYPE_p_unsigned___int32 TimeStamp, bool bndchk) {
    int ret = ccl_dllDPINVOKE.CigiSOFV4_SetTimeStamp__SWIG_0(swigCPtr, SWIGTYPE_p_unsigned___int32.getCPtr(TimeStamp), bndchk);
    if (ccl_dllDPINVOKE.SWIGPendingException.Pending) throw ccl_dllDPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int SetTimeStamp(SWIGTYPE_p_unsigned___int32 TimeStamp) {
    int ret = ccl_dllDPINVOKE.CigiSOFV4_SetTimeStamp__SWIG_1(swigCPtr, SWIGTYPE_p_unsigned___int32.getCPtr(TimeStamp));
    if (ccl_dllDPINVOKE.SWIGPendingException.Pending) throw ccl_dllDPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool GetTimeStampValid() {
    bool ret = ccl_dllDPINVOKE.CigiSOFV4_GetTimeStampValid(swigCPtr);
    return ret;
  }

  public int SetTimeStampValid(bool TimeStampValidIn, bool bndchk) {
    int ret = ccl_dllDPINVOKE.CigiSOFV4_SetTimeStampValid__SWIG_0(swigCPtr, TimeStampValidIn, bndchk);
    return ret;
  }

  public int SetTimeStampValid(bool TimeStampValidIn) {
    int ret = ccl_dllDPINVOKE.CigiSOFV4_SetTimeStampValid__SWIG_1(swigCPtr, TimeStampValidIn);
    return ret;
  }

  public CigiBaseSOF.EarthRefModelGrp GetEarthRefModel() {
    CigiBaseSOF.EarthRefModelGrp ret = (CigiBaseSOF.EarthRefModelGrp)ccl_dllDPINVOKE.CigiSOFV4_GetEarthRefModel(swigCPtr);
    return ret;
  }

  public int SetEarthRefModel(CigiBaseSOF.EarthRefModelGrp EarthRefModelIn, bool bndchk) {
    int ret = ccl_dllDPINVOKE.CigiSOFV4_SetEarthRefModel__SWIG_0(swigCPtr, (int)EarthRefModelIn, bndchk);
    return ret;
  }

  public int SetEarthRefModel(CigiBaseSOF.EarthRefModelGrp EarthRefModelIn) {
    int ret = ccl_dllDPINVOKE.CigiSOFV4_SetEarthRefModel__SWIG_1(swigCPtr, (int)EarthRefModelIn);
    return ret;
  }

  public SWIGTYPE_p_unsigned___int32 GetLastRcvdHostFrame() {
    SWIGTYPE_p_unsigned___int32 ret = new SWIGTYPE_p_unsigned___int32(ccl_dllDPINVOKE.CigiSOFV4_GetLastRcvdHostFrame(swigCPtr), true);
    return ret;
  }

  public int SetLastRcvdHostFrame(SWIGTYPE_p_unsigned___int32 LastRcvdHostFrameIn, bool bndchk) {
    int ret = ccl_dllDPINVOKE.CigiSOFV4_SetLastRcvdHostFrame__SWIG_0(swigCPtr, SWIGTYPE_p_unsigned___int32.getCPtr(LastRcvdHostFrameIn), bndchk);
    if (ccl_dllDPINVOKE.SWIGPendingException.Pending) throw ccl_dllDPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int SetLastRcvdHostFrame(SWIGTYPE_p_unsigned___int32 LastRcvdHostFrameIn) {
    int ret = ccl_dllDPINVOKE.CigiSOFV4_SetLastRcvdHostFrame__SWIG_1(swigCPtr, SWIGTYPE_p_unsigned___int32.getCPtr(LastRcvdHostFrameIn));
    if (ccl_dllDPINVOKE.SWIGPendingException.Pending) throw ccl_dllDPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_unsigned___int8 GetOverframingCondidtion() {
    SWIGTYPE_p_unsigned___int8 ret = new SWIGTYPE_p_unsigned___int8(ccl_dllDPINVOKE.CigiSOFV4_GetOverframingCondidtion(swigCPtr), true);
    return ret;
  }

  public int SetOverframingCondidtion(SWIGTYPE_p_unsigned___int8 OverframingIn, bool bndchk) {
    int ret = ccl_dllDPINVOKE.CigiSOFV4_SetOverframingCondidtion__SWIG_0(swigCPtr, SWIGTYPE_p_unsigned___int8.getCPtr(OverframingIn), bndchk);
    if (ccl_dllDPINVOKE.SWIGPendingException.Pending) throw ccl_dllDPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int SetOverframingCondidtion(SWIGTYPE_p_unsigned___int8 OverframingIn) {
    int ret = ccl_dllDPINVOKE.CigiSOFV4_SetOverframingCondidtion__SWIG_1(swigCPtr, SWIGTYPE_p_unsigned___int8.getCPtr(OverframingIn));
    if (ccl_dllDPINVOKE.SWIGPendingException.Pending) throw ccl_dllDPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_unsigned___int8 GetPagingCondition() {
    SWIGTYPE_p_unsigned___int8 ret = new SWIGTYPE_p_unsigned___int8(ccl_dllDPINVOKE.CigiSOFV4_GetPagingCondition(swigCPtr), true);
    return ret;
  }

  public int SetPagingCondition(SWIGTYPE_p_unsigned___int8 PagingConditionIn, bool bndchk) {
    int ret = ccl_dllDPINVOKE.CigiSOFV4_SetPagingCondition__SWIG_0(swigCPtr, SWIGTYPE_p_unsigned___int8.getCPtr(PagingConditionIn), bndchk);
    if (ccl_dllDPINVOKE.SWIGPendingException.Pending) throw ccl_dllDPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int SetPagingCondition(SWIGTYPE_p_unsigned___int8 PagingConditionIn) {
    int ret = ccl_dllDPINVOKE.CigiSOFV4_SetPagingCondition__SWIG_1(swigCPtr, SWIGTYPE_p_unsigned___int8.getCPtr(PagingConditionIn));
    if (ccl_dllDPINVOKE.SWIGPendingException.Pending) throw ccl_dllDPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_unsigned___int8 GetExcessiveDataCondition() {
    SWIGTYPE_p_unsigned___int8 ret = new SWIGTYPE_p_unsigned___int8(ccl_dllDPINVOKE.CigiSOFV4_GetExcessiveDataCondition(swigCPtr), true);
    return ret;
  }

  public int SetExcessiveDataCondition(SWIGTYPE_p_unsigned___int8 ExcessVarLenDataConditionIn, bool bndchk) {
    int ret = ccl_dllDPINVOKE.CigiSOFV4_SetExcessiveDataCondition__SWIG_0(swigCPtr, SWIGTYPE_p_unsigned___int8.getCPtr(ExcessVarLenDataConditionIn), bndchk);
    if (ccl_dllDPINVOKE.SWIGPendingException.Pending) throw ccl_dllDPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int SetExcessiveDataCondition(SWIGTYPE_p_unsigned___int8 ExcessVarLenDataConditionIn) {
    int ret = ccl_dllDPINVOKE.CigiSOFV4_SetExcessiveDataCondition__SWIG_1(swigCPtr, SWIGTYPE_p_unsigned___int8.getCPtr(ExcessVarLenDataConditionIn));
    if (ccl_dllDPINVOKE.SWIGPendingException.Pending) throw ccl_dllDPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
