//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class CigiHatHotReqV3 : CigiBaseHatHotReq {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal CigiHatHotReqV3(global::System.IntPtr cPtr, bool cMemoryOwn) : base(ccl_dllDPINVOKE.CigiHatHotReqV3_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CigiHatHotReqV3 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CigiHatHotReqV3 obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ccl_dllDPINVOKE.delete_CigiHatHotReqV3(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public CigiHatHotReqV3() : this(ccl_dllDPINVOKE.new_CigiHatHotReqV3(), true) {
  }

  public override int Pack(CigiBasePacket Base, SWIGTYPE_p_unsigned___int8 Buff, SWIGTYPE_p_void Spec) {
    int ret = ccl_dllDPINVOKE.CigiHatHotReqV3_Pack(swigCPtr, CigiBasePacket.getCPtr(Base), SWIGTYPE_p_unsigned___int8.getCPtr(Buff), SWIGTYPE_p_void.getCPtr(Spec));
    return ret;
  }

  public override int Unpack(SWIGTYPE_p_unsigned___int8 Buff, bool Swap, SWIGTYPE_p_void Spec) {
    int ret = ccl_dllDPINVOKE.CigiHatHotReqV3_Unpack(swigCPtr, SWIGTYPE_p_unsigned___int8.getCPtr(Buff), Swap, SWIGTYPE_p_void.getCPtr(Spec));
    return ret;
  }

  public override int GetCnvt(CigiVersionID CnvtVersion, SWIGTYPE_p_CigiCnvtInfoType__Type CnvtInfo) {
    int ret = ccl_dllDPINVOKE.CigiHatHotReqV3_GetCnvt(swigCPtr, CigiVersionID.getCPtr(CnvtVersion), SWIGTYPE_p_CigiCnvtInfoType__Type.getCPtr(CnvtInfo));
    if (ccl_dllDPINVOKE.SWIGPendingException.Pending) throw ccl_dllDPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int SetReqType(CigiBaseHatHotReq.ReqTypeGrp ReqTypeIn, bool bndchk) {
    int ret = ccl_dllDPINVOKE.CigiHatHotReqV3_SetReqType__SWIG_0(swigCPtr, (int)ReqTypeIn, bndchk);
    return ret;
  }

  public int SetReqType(CigiBaseHatHotReq.ReqTypeGrp ReqTypeIn) {
    int ret = ccl_dllDPINVOKE.CigiHatHotReqV3_SetReqType__SWIG_1(swigCPtr, (int)ReqTypeIn);
    return ret;
  }

  public CigiBaseHatHotReq.ReqTypeGrp GetReqType() {
    CigiBaseHatHotReq.ReqTypeGrp ret = (CigiBaseHatHotReq.ReqTypeGrp)ccl_dllDPINVOKE.CigiHatHotReqV3_GetReqType(swigCPtr);
    return ret;
  }

  public int SetSrcCoordSys(CigiBaseHatHotReq.CoordSysGrp SrcCoordSysIn, bool bndchk) {
    int ret = ccl_dllDPINVOKE.CigiHatHotReqV3_SetSrcCoordSys__SWIG_0(swigCPtr, (int)SrcCoordSysIn, bndchk);
    return ret;
  }

  public int SetSrcCoordSys(CigiBaseHatHotReq.CoordSysGrp SrcCoordSysIn) {
    int ret = ccl_dllDPINVOKE.CigiHatHotReqV3_SetSrcCoordSys__SWIG_1(swigCPtr, (int)SrcCoordSysIn);
    return ret;
  }

  public CigiBaseHatHotReq.CoordSysGrp GetSrcCoordSys() {
    CigiBaseHatHotReq.CoordSysGrp ret = (CigiBaseHatHotReq.CoordSysGrp)ccl_dllDPINVOKE.CigiHatHotReqV3_GetSrcCoordSys(swigCPtr);
    return ret;
  }

  public int SetEntityID(SWIGTYPE_p_unsigned___int16 EntityIDIn, bool bndchk) {
    int ret = ccl_dllDPINVOKE.CigiHatHotReqV3_SetEntityID__SWIG_0(swigCPtr, SWIGTYPE_p_unsigned___int16.getCPtr(EntityIDIn), bndchk);
    if (ccl_dllDPINVOKE.SWIGPendingException.Pending) throw ccl_dllDPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int SetEntityID(SWIGTYPE_p_unsigned___int16 EntityIDIn) {
    int ret = ccl_dllDPINVOKE.CigiHatHotReqV3_SetEntityID__SWIG_1(swigCPtr, SWIGTYPE_p_unsigned___int16.getCPtr(EntityIDIn));
    if (ccl_dllDPINVOKE.SWIGPendingException.Pending) throw ccl_dllDPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_unsigned___int16 GetEntityID() {
    SWIGTYPE_p_unsigned___int16 ret = new SWIGTYPE_p_unsigned___int16(ccl_dllDPINVOKE.CigiHatHotReqV3_GetEntityID(swigCPtr), true);
    return ret;
  }

  public int SetXoff(double XoffIn, bool bndchk) {
    int ret = ccl_dllDPINVOKE.CigiHatHotReqV3_SetXoff__SWIG_0(swigCPtr, XoffIn, bndchk);
    return ret;
  }

  public int SetXoff(double XoffIn) {
    int ret = ccl_dllDPINVOKE.CigiHatHotReqV3_SetXoff__SWIG_1(swigCPtr, XoffIn);
    return ret;
  }

  public double GetXoff() {
    double ret = ccl_dllDPINVOKE.CigiHatHotReqV3_GetXoff(swigCPtr);
    return ret;
  }

  public int SetYoff(double YoffIn, bool bndchk) {
    int ret = ccl_dllDPINVOKE.CigiHatHotReqV3_SetYoff__SWIG_0(swigCPtr, YoffIn, bndchk);
    return ret;
  }

  public int SetYoff(double YoffIn) {
    int ret = ccl_dllDPINVOKE.CigiHatHotReqV3_SetYoff__SWIG_1(swigCPtr, YoffIn);
    return ret;
  }

  public double GetYoff() {
    double ret = ccl_dllDPINVOKE.CigiHatHotReqV3_GetYoff(swigCPtr);
    return ret;
  }

  public int SetAlt(double AltIn, bool bndchk) {
    int ret = ccl_dllDPINVOKE.CigiHatHotReqV3_SetAlt__SWIG_0(swigCPtr, AltIn, bndchk);
    return ret;
  }

  public int SetAlt(double AltIn) {
    int ret = ccl_dllDPINVOKE.CigiHatHotReqV3_SetAlt__SWIG_1(swigCPtr, AltIn);
    return ret;
  }

  public double GetAlt() {
    double ret = ccl_dllDPINVOKE.CigiHatHotReqV3_GetAlt(swigCPtr);
    return ret;
  }

  public int SetZoff(double ZoffIn, bool bndchk) {
    int ret = ccl_dllDPINVOKE.CigiHatHotReqV3_SetZoff__SWIG_0(swigCPtr, ZoffIn, bndchk);
    return ret;
  }

  public int SetZoff(double ZoffIn) {
    int ret = ccl_dllDPINVOKE.CigiHatHotReqV3_SetZoff__SWIG_1(swigCPtr, ZoffIn);
    return ret;
  }

  public double GetZoff() {
    double ret = ccl_dllDPINVOKE.CigiHatHotReqV3_GetZoff(swigCPtr);
    return ret;
  }

}
