//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class CigiRateCtrlV3_2 : CigiBaseRateCtrl {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal CigiRateCtrlV3_2(global::System.IntPtr cPtr, bool cMemoryOwn) : base(example_modulePINVOKE.CigiRateCtrlV3_2_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CigiRateCtrlV3_2 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CigiRateCtrlV3_2 obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          example_modulePINVOKE.delete_CigiRateCtrlV3_2(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public CigiRateCtrlV3_2() : this(example_modulePINVOKE.new_CigiRateCtrlV3_2(), true) {
  }

  public override int Pack(CigiBasePacket Base, SWIGTYPE_p_unsigned___int8 Buff, SWIGTYPE_p_void Spec) {
    int ret = example_modulePINVOKE.CigiRateCtrlV3_2_Pack(swigCPtr, CigiBasePacket.getCPtr(Base), SWIGTYPE_p_unsigned___int8.getCPtr(Buff), SWIGTYPE_p_void.getCPtr(Spec));
    return ret;
  }

  public override int Unpack(SWIGTYPE_p_unsigned___int8 Buff, bool Swap, SWIGTYPE_p_void Spec) {
    int ret = example_modulePINVOKE.CigiRateCtrlV3_2_Unpack(swigCPtr, SWIGTYPE_p_unsigned___int8.getCPtr(Buff), Swap, SWIGTYPE_p_void.getCPtr(Spec));
    return ret;
  }

  public int SetArtPartID(SWIGTYPE_p_unsigned___int8 ArtPartIDIn, bool bndchk) {
    int ret = example_modulePINVOKE.CigiRateCtrlV3_2_SetArtPartID__SWIG_0(swigCPtr, SWIGTYPE_p_unsigned___int8.getCPtr(ArtPartIDIn), bndchk);
    if (example_modulePINVOKE.SWIGPendingException.Pending) throw example_modulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int SetArtPartID(SWIGTYPE_p_unsigned___int8 ArtPartIDIn) {
    int ret = example_modulePINVOKE.CigiRateCtrlV3_2_SetArtPartID__SWIG_1(swigCPtr, SWIGTYPE_p_unsigned___int8.getCPtr(ArtPartIDIn));
    if (example_modulePINVOKE.SWIGPendingException.Pending) throw example_modulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_unsigned___int8 GetArtPartID() {
    SWIGTYPE_p_unsigned___int8 ret = new SWIGTYPE_p_unsigned___int8(example_modulePINVOKE.CigiRateCtrlV3_2_GetArtPartID(swigCPtr), true);
    return ret;
  }

  public int SetApplyToArtPart(bool ApplyToArtPartIn, bool bndchk) {
    int ret = example_modulePINVOKE.CigiRateCtrlV3_2_SetApplyToArtPart__SWIG_0(swigCPtr, ApplyToArtPartIn, bndchk);
    return ret;
  }

  public int SetApplyToArtPart(bool ApplyToArtPartIn) {
    int ret = example_modulePINVOKE.CigiRateCtrlV3_2_SetApplyToArtPart__SWIG_1(swigCPtr, ApplyToArtPartIn);
    return ret;
  }

  public bool GetApplyToArtPart() {
    bool ret = example_modulePINVOKE.CigiRateCtrlV3_2_GetApplyToArtPart(swigCPtr);
    return ret;
  }

  public int SetCoordSys(CigiBaseRateCtrl.CoordSysGrp CoordSysIn, bool bndchk) {
    int ret = example_modulePINVOKE.CigiRateCtrlV3_2_SetCoordSys__SWIG_0(swigCPtr, (int)CoordSysIn, bndchk);
    return ret;
  }

  public int SetCoordSys(CigiBaseRateCtrl.CoordSysGrp CoordSysIn) {
    int ret = example_modulePINVOKE.CigiRateCtrlV3_2_SetCoordSys__SWIG_1(swigCPtr, (int)CoordSysIn);
    return ret;
  }

  public CigiBaseRateCtrl.CoordSysGrp GetCoordSys() {
    CigiBaseRateCtrl.CoordSysGrp ret = (CigiBaseRateCtrl.CoordSysGrp)example_modulePINVOKE.CigiRateCtrlV3_2_GetCoordSys(swigCPtr);
    return ret;
  }

}
