//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class CigiHatHotXRespV3 : CigiBaseHatHotResp {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal CigiHatHotXRespV3(global::System.IntPtr cPtr, bool cMemoryOwn) : base(ccl_dllDPINVOKE.CigiHatHotXRespV3_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CigiHatHotXRespV3 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CigiHatHotXRespV3 obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ccl_dllDPINVOKE.delete_CigiHatHotXRespV3(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public CigiHatHotXRespV3() : this(ccl_dllDPINVOKE.new_CigiHatHotXRespV3(), true) {
  }

  public override int Pack(CigiBasePacket Base, SWIGTYPE_p_unsigned___int8 Buff, SWIGTYPE_p_void Spec) {
    int ret = ccl_dllDPINVOKE.CigiHatHotXRespV3_Pack(swigCPtr, CigiBasePacket.getCPtr(Base), SWIGTYPE_p_unsigned___int8.getCPtr(Buff), SWIGTYPE_p_void.getCPtr(Spec));
    return ret;
  }

  public override int Unpack(SWIGTYPE_p_unsigned___int8 Buff, bool Swap, SWIGTYPE_p_void Spec) {
    int ret = ccl_dllDPINVOKE.CigiHatHotXRespV3_Unpack(swigCPtr, SWIGTYPE_p_unsigned___int8.getCPtr(Buff), Swap, SWIGTYPE_p_void.getCPtr(Spec));
    return ret;
  }

  public override int GetCnvt(CigiVersionID CnvtVersion, SWIGTYPE_p_CigiCnvtInfoType__Type CnvtInfo) {
    int ret = ccl_dllDPINVOKE.CigiHatHotXRespV3_GetCnvt(swigCPtr, CigiVersionID.getCPtr(CnvtVersion), SWIGTYPE_p_CigiCnvtInfoType__Type.getCPtr(CnvtInfo));
    if (ccl_dllDPINVOKE.SWIGPendingException.Pending) throw ccl_dllDPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int SetHat(double HatIn, bool bndchk) {
    int ret = ccl_dllDPINVOKE.CigiHatHotXRespV3_SetHat__SWIG_0(swigCPtr, HatIn, bndchk);
    return ret;
  }

  public int SetHat(double HatIn) {
    int ret = ccl_dllDPINVOKE.CigiHatHotXRespV3_SetHat__SWIG_1(swigCPtr, HatIn);
    return ret;
  }

  public double GetHat() {
    double ret = ccl_dllDPINVOKE.CigiHatHotXRespV3_GetHat(swigCPtr);
    return ret;
  }

  public int SetHot(double HotIn, bool bndchk) {
    int ret = ccl_dllDPINVOKE.CigiHatHotXRespV3_SetHot__SWIG_0(swigCPtr, HotIn, bndchk);
    return ret;
  }

  public int SetHot(double HotIn) {
    int ret = ccl_dllDPINVOKE.CigiHatHotXRespV3_SetHot__SWIG_1(swigCPtr, HotIn);
    return ret;
  }

  public double GetHot() {
    double ret = ccl_dllDPINVOKE.CigiHatHotXRespV3_GetHot(swigCPtr);
    return ret;
  }

  public int SetMaterial(SWIGTYPE_p_unsigned___int32 MaterialIn, bool bndchk) {
    int ret = ccl_dllDPINVOKE.CigiHatHotXRespV3_SetMaterial__SWIG_0(swigCPtr, SWIGTYPE_p_unsigned___int32.getCPtr(MaterialIn), bndchk);
    if (ccl_dllDPINVOKE.SWIGPendingException.Pending) throw ccl_dllDPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int SetMaterial(SWIGTYPE_p_unsigned___int32 MaterialIn) {
    int ret = ccl_dllDPINVOKE.CigiHatHotXRespV3_SetMaterial__SWIG_1(swigCPtr, SWIGTYPE_p_unsigned___int32.getCPtr(MaterialIn));
    if (ccl_dllDPINVOKE.SWIGPendingException.Pending) throw ccl_dllDPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_unsigned___int32 GetMaterial() {
    SWIGTYPE_p_unsigned___int32 ret = new SWIGTYPE_p_unsigned___int32(ccl_dllDPINVOKE.CigiHatHotXRespV3_GetMaterial(swigCPtr), true);
    return ret;
  }

  public int SetNormAz(float NormAzIn, bool bndchk) {
    int ret = ccl_dllDPINVOKE.CigiHatHotXRespV3_SetNormAz__SWIG_0(swigCPtr, NormAzIn, bndchk);
    return ret;
  }

  public int SetNormAz(float NormAzIn) {
    int ret = ccl_dllDPINVOKE.CigiHatHotXRespV3_SetNormAz__SWIG_1(swigCPtr, NormAzIn);
    return ret;
  }

  public float GetNormAz() {
    float ret = ccl_dllDPINVOKE.CigiHatHotXRespV3_GetNormAz(swigCPtr);
    return ret;
  }

  public int SetNormEl(float NormElIn, bool bndchk) {
    int ret = ccl_dllDPINVOKE.CigiHatHotXRespV3_SetNormEl__SWIG_0(swigCPtr, NormElIn, bndchk);
    return ret;
  }

  public int SetNormEl(float NormElIn) {
    int ret = ccl_dllDPINVOKE.CigiHatHotXRespV3_SetNormEl__SWIG_1(swigCPtr, NormElIn);
    return ret;
  }

  public float GetNormEl() {
    float ret = ccl_dllDPINVOKE.CigiHatHotXRespV3_GetNormEl(swigCPtr);
    return ret;
  }

}
