//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class CigiCollDetSegRespV1 : CigiBaseCollDetSegResp {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal CigiCollDetSegRespV1(global::System.IntPtr cPtr, bool cMemoryOwn) : base(ccl_dllDPINVOKE.CigiCollDetSegRespV1_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CigiCollDetSegRespV1 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CigiCollDetSegRespV1 obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ccl_dllDPINVOKE.delete_CigiCollDetSegRespV1(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public CigiCollDetSegRespV1() : this(ccl_dllDPINVOKE.new_CigiCollDetSegRespV1(), true) {
  }

  public override int Pack(CigiBasePacket Base, SWIGTYPE_p_unsigned___int8 Buff, SWIGTYPE_p_void Spec) {
    int ret = ccl_dllDPINVOKE.CigiCollDetSegRespV1_Pack(swigCPtr, CigiBasePacket.getCPtr(Base), SWIGTYPE_p_unsigned___int8.getCPtr(Buff), SWIGTYPE_p_void.getCPtr(Spec));
    return ret;
  }

  public override int Unpack(SWIGTYPE_p_unsigned___int8 Buff, bool Swap, SWIGTYPE_p_void Spec) {
    int ret = ccl_dllDPINVOKE.CigiCollDetSegRespV1_Unpack(swigCPtr, SWIGTYPE_p_unsigned___int8.getCPtr(Buff), Swap, SWIGTYPE_p_void.getCPtr(Spec));
    return ret;
  }

  public int SetSegID(SWIGTYPE_p_unsigned___int8 SegIDIn, bool bndchk) {
    int ret = ccl_dllDPINVOKE.CigiCollDetSegRespV1_SetSegID__SWIG_0(swigCPtr, SWIGTYPE_p_unsigned___int8.getCPtr(SegIDIn), bndchk);
    if (ccl_dllDPINVOKE.SWIGPendingException.Pending) throw ccl_dllDPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int SetSegID(SWIGTYPE_p_unsigned___int8 SegIDIn) {
    int ret = ccl_dllDPINVOKE.CigiCollDetSegRespV1_SetSegID__SWIG_1(swigCPtr, SWIGTYPE_p_unsigned___int8.getCPtr(SegIDIn));
    if (ccl_dllDPINVOKE.SWIGPendingException.Pending) throw ccl_dllDPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_unsigned___int8 GetSegID() {
    SWIGTYPE_p_unsigned___int8 ret = new SWIGTYPE_p_unsigned___int8(ccl_dllDPINVOKE.CigiCollDetSegRespV1_GetSegID(swigCPtr), true);
    return ret;
  }

  public int SetX(float XIn, bool bndchk) {
    int ret = ccl_dllDPINVOKE.CigiCollDetSegRespV1_SetX__SWIG_0(swigCPtr, XIn, bndchk);
    return ret;
  }

  public int SetX(float XIn) {
    int ret = ccl_dllDPINVOKE.CigiCollDetSegRespV1_SetX__SWIG_1(swigCPtr, XIn);
    return ret;
  }

  public float GetX() {
    float ret = ccl_dllDPINVOKE.CigiCollDetSegRespV1_GetX(swigCPtr);
    return ret;
  }

  public int SetY(float YIn, bool bndchk) {
    int ret = ccl_dllDPINVOKE.CigiCollDetSegRespV1_SetY__SWIG_0(swigCPtr, YIn, bndchk);
    return ret;
  }

  public int SetY(float YIn) {
    int ret = ccl_dllDPINVOKE.CigiCollDetSegRespV1_SetY__SWIG_1(swigCPtr, YIn);
    return ret;
  }

  public float GetY() {
    float ret = ccl_dllDPINVOKE.CigiCollDetSegRespV1_GetY(swigCPtr);
    return ret;
  }

  public int SetZ(float ZIn, bool bndchk) {
    int ret = ccl_dllDPINVOKE.CigiCollDetSegRespV1_SetZ__SWIG_0(swigCPtr, ZIn, bndchk);
    return ret;
  }

  public int SetZ(float ZIn) {
    int ret = ccl_dllDPINVOKE.CigiCollDetSegRespV1_SetZ__SWIG_1(swigCPtr, ZIn);
    return ret;
  }

  public float GetZ() {
    float ret = ccl_dllDPINVOKE.CigiCollDetSegRespV1_GetZ(swigCPtr);
    return ret;
  }

}
