//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class CigiEntityCtrlV3 : CigiBaseEntityCtrl {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal CigiEntityCtrlV3(global::System.IntPtr cPtr, bool cMemoryOwn) : base(ccl_dllDPINVOKE.CigiEntityCtrlV3_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CigiEntityCtrlV3 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CigiEntityCtrlV3 obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ccl_dllDPINVOKE.delete_CigiEntityCtrlV3(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public CigiEntityCtrlV3() : this(ccl_dllDPINVOKE.new_CigiEntityCtrlV3(), true) {
  }

  public override int Pack(CigiBasePacket Base, SWIGTYPE_p_unsigned___int8 Buff, SWIGTYPE_p_void Spec) {
    int ret = ccl_dllDPINVOKE.CigiEntityCtrlV3_Pack(swigCPtr, CigiBasePacket.getCPtr(Base), SWIGTYPE_p_unsigned___int8.getCPtr(Buff), SWIGTYPE_p_void.getCPtr(Spec));
    return ret;
  }

  public override int Unpack(SWIGTYPE_p_unsigned___int8 Buff, bool Swap, SWIGTYPE_p_void Spec) {
    int ret = ccl_dllDPINVOKE.CigiEntityCtrlV3_Unpack(swigCPtr, SWIGTYPE_p_unsigned___int8.getCPtr(Buff), Swap, SWIGTYPE_p_void.getCPtr(Spec));
    return ret;
  }

  public int SetAlpha(SWIGTYPE_p_unsigned___int8 AlphaIn, bool bndchk) {
    int ret = ccl_dllDPINVOKE.CigiEntityCtrlV3_SetAlpha__SWIG_0(swigCPtr, SWIGTYPE_p_unsigned___int8.getCPtr(AlphaIn), bndchk);
    if (ccl_dllDPINVOKE.SWIGPendingException.Pending) throw ccl_dllDPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int SetAlpha(SWIGTYPE_p_unsigned___int8 AlphaIn) {
    int ret = ccl_dllDPINVOKE.CigiEntityCtrlV3_SetAlpha__SWIG_1(swigCPtr, SWIGTYPE_p_unsigned___int8.getCPtr(AlphaIn));
    if (ccl_dllDPINVOKE.SWIGPendingException.Pending) throw ccl_dllDPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_unsigned___int8 GetAlpha() {
    SWIGTYPE_p_unsigned___int8 ret = new SWIGTYPE_p_unsigned___int8(ccl_dllDPINVOKE.CigiEntityCtrlV3_GetAlpha(swigCPtr), true);
    return ret;
  }

  public int SetYaw(float YawIn, bool bndchk) {
    int ret = ccl_dllDPINVOKE.CigiEntityCtrlV3_SetYaw__SWIG_0(swigCPtr, YawIn, bndchk);
    return ret;
  }

  public int SetYaw(float YawIn) {
    int ret = ccl_dllDPINVOKE.CigiEntityCtrlV3_SetYaw__SWIG_1(swigCPtr, YawIn);
    return ret;
  }

  public float GetYaw() {
    float ret = ccl_dllDPINVOKE.CigiEntityCtrlV3_GetYaw(swigCPtr);
    return ret;
  }

  public int SetParentID(SWIGTYPE_p_unsigned___int16 ParentIDIn, bool bndchk) {
    int ret = ccl_dllDPINVOKE.CigiEntityCtrlV3_SetParentID__SWIG_0(swigCPtr, SWIGTYPE_p_unsigned___int16.getCPtr(ParentIDIn), bndchk);
    if (ccl_dllDPINVOKE.SWIGPendingException.Pending) throw ccl_dllDPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int SetParentID(SWIGTYPE_p_unsigned___int16 ParentIDIn) {
    int ret = ccl_dllDPINVOKE.CigiEntityCtrlV3_SetParentID__SWIG_1(swigCPtr, SWIGTYPE_p_unsigned___int16.getCPtr(ParentIDIn));
    if (ccl_dllDPINVOKE.SWIGPendingException.Pending) throw ccl_dllDPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_unsigned___int16 GetParentID() {
    SWIGTYPE_p_unsigned___int16 ret = new SWIGTYPE_p_unsigned___int16(ccl_dllDPINVOKE.CigiEntityCtrlV3_GetParentID(swigCPtr), true);
    return ret;
  }

  public int SetPitch(float PitchIn, bool bndchk) {
    int ret = ccl_dllDPINVOKE.CigiEntityCtrlV3_SetPitch__SWIG_0(swigCPtr, PitchIn, bndchk);
    return ret;
  }

  public int SetPitch(float PitchIn) {
    int ret = ccl_dllDPINVOKE.CigiEntityCtrlV3_SetPitch__SWIG_1(swigCPtr, PitchIn);
    return ret;
  }

  public float GetPitch() {
    float ret = ccl_dllDPINVOKE.CigiEntityCtrlV3_GetPitch(swigCPtr);
    return ret;
  }

  public int SetRoll(float RollIn, bool bndchk) {
    int ret = ccl_dllDPINVOKE.CigiEntityCtrlV3_SetRoll__SWIG_0(swigCPtr, RollIn, bndchk);
    return ret;
  }

  public int SetRoll(float RollIn) {
    int ret = ccl_dllDPINVOKE.CigiEntityCtrlV3_SetRoll__SWIG_1(swigCPtr, RollIn);
    return ret;
  }

  public float GetRoll() {
    float ret = ccl_dllDPINVOKE.CigiEntityCtrlV3_GetRoll(swigCPtr);
    return ret;
  }

  public int SetLat(double Lat, bool bndchk) {
    int ret = ccl_dllDPINVOKE.CigiEntityCtrlV3_SetLat__SWIG_0(swigCPtr, Lat, bndchk);
    return ret;
  }

  public int SetLat(double Lat) {
    int ret = ccl_dllDPINVOKE.CigiEntityCtrlV3_SetLat__SWIG_1(swigCPtr, Lat);
    return ret;
  }

  public double GetLat() {
    double ret = ccl_dllDPINVOKE.CigiEntityCtrlV3_GetLat(swigCPtr);
    return ret;
  }

  public int SetXoff(double Xoff, bool bndchk) {
    int ret = ccl_dllDPINVOKE.CigiEntityCtrlV3_SetXoff__SWIG_0(swigCPtr, Xoff, bndchk);
    return ret;
  }

  public int SetXoff(double Xoff) {
    int ret = ccl_dllDPINVOKE.CigiEntityCtrlV3_SetXoff__SWIG_1(swigCPtr, Xoff);
    return ret;
  }

  public double GetXoff() {
    double ret = ccl_dllDPINVOKE.CigiEntityCtrlV3_GetXoff(swigCPtr);
    return ret;
  }

  public int SetLon(double Lon, bool bndchk) {
    int ret = ccl_dllDPINVOKE.CigiEntityCtrlV3_SetLon__SWIG_0(swigCPtr, Lon, bndchk);
    return ret;
  }

  public int SetLon(double Lon) {
    int ret = ccl_dllDPINVOKE.CigiEntityCtrlV3_SetLon__SWIG_1(swigCPtr, Lon);
    return ret;
  }

  public double GetLon() {
    double ret = ccl_dllDPINVOKE.CigiEntityCtrlV3_GetLon(swigCPtr);
    return ret;
  }

  public int SetYoff(double Yoff, bool bndchk) {
    int ret = ccl_dllDPINVOKE.CigiEntityCtrlV3_SetYoff__SWIG_0(swigCPtr, Yoff, bndchk);
    return ret;
  }

  public int SetYoff(double Yoff) {
    int ret = ccl_dllDPINVOKE.CigiEntityCtrlV3_SetYoff__SWIG_1(swigCPtr, Yoff);
    return ret;
  }

  public double GetYoff() {
    double ret = ccl_dllDPINVOKE.CigiEntityCtrlV3_GetYoff(swigCPtr);
    return ret;
  }

  public int SetAttachState(CigiBaseEntityCtrl.AttachStateGrp AttachStateIn, bool bndchk) {
    int ret = ccl_dllDPINVOKE.CigiEntityCtrlV3_SetAttachState__SWIG_0(swigCPtr, (int)AttachStateIn, bndchk);
    return ret;
  }

  public int SetAttachState(CigiBaseEntityCtrl.AttachStateGrp AttachStateIn) {
    int ret = ccl_dllDPINVOKE.CigiEntityCtrlV3_SetAttachState__SWIG_1(swigCPtr, (int)AttachStateIn);
    return ret;
  }

  public CigiBaseEntityCtrl.AttachStateGrp GetAttachState() {
    CigiBaseEntityCtrl.AttachStateGrp ret = (CigiBaseEntityCtrl.AttachStateGrp)ccl_dllDPINVOKE.CigiEntityCtrlV3_GetAttachState(swigCPtr);
    return ret;
  }

  public int SetAlt(double Alt, bool bndchk) {
    int ret = ccl_dllDPINVOKE.CigiEntityCtrlV3_SetAlt__SWIG_0(swigCPtr, Alt, bndchk);
    return ret;
  }

  public int SetAlt(double Alt) {
    int ret = ccl_dllDPINVOKE.CigiEntityCtrlV3_SetAlt__SWIG_1(swigCPtr, Alt);
    return ret;
  }

  public double GetAlt() {
    double ret = ccl_dllDPINVOKE.CigiEntityCtrlV3_GetAlt(swigCPtr);
    return ret;
  }

  public int SetZoff(double Zoff, bool bndchk) {
    int ret = ccl_dllDPINVOKE.CigiEntityCtrlV3_SetZoff__SWIG_0(swigCPtr, Zoff, bndchk);
    return ret;
  }

  public int SetZoff(double Zoff) {
    int ret = ccl_dllDPINVOKE.CigiEntityCtrlV3_SetZoff__SWIG_1(swigCPtr, Zoff);
    return ret;
  }

  public double GetZoff() {
    double ret = ccl_dllDPINVOKE.CigiEntityCtrlV3_GetZoff(swigCPtr);
    return ret;
  }

  public int SetEntityState(CigiBaseEntityCtrl.EntityStateGrp EntityStateIn, bool bndchk) {
    int ret = ccl_dllDPINVOKE.CigiEntityCtrlV3_SetEntityState__SWIG_0(swigCPtr, (int)EntityStateIn, bndchk);
    return ret;
  }

  public int SetEntityState(CigiBaseEntityCtrl.EntityStateGrp EntityStateIn) {
    int ret = ccl_dllDPINVOKE.CigiEntityCtrlV3_SetEntityState__SWIG_1(swigCPtr, (int)EntityStateIn);
    return ret;
  }

  public CigiBaseEntityCtrl.EntityStateGrp GetEntityState() {
    CigiBaseEntityCtrl.EntityStateGrp ret = (CigiBaseEntityCtrl.EntityStateGrp)ccl_dllDPINVOKE.CigiEntityCtrlV3_GetEntityState(swigCPtr);
    return ret;
  }

  public int SetGrndClamp(CigiBaseEntityCtrl.GrndClampGrp GrndClampIn, bool bndchk) {
    int ret = ccl_dllDPINVOKE.CigiEntityCtrlV3_SetGrndClamp__SWIG_0(swigCPtr, (int)GrndClampIn, bndchk);
    return ret;
  }

  public int SetGrndClamp(CigiBaseEntityCtrl.GrndClampGrp GrndClampIn) {
    int ret = ccl_dllDPINVOKE.CigiEntityCtrlV3_SetGrndClamp__SWIG_1(swigCPtr, (int)GrndClampIn);
    return ret;
  }

  public CigiBaseEntityCtrl.GrndClampGrp GetGrndClamp() {
    CigiBaseEntityCtrl.GrndClampGrp ret = (CigiBaseEntityCtrl.GrndClampGrp)ccl_dllDPINVOKE.CigiEntityCtrlV3_GetGrndClamp(swigCPtr);
    return ret;
  }

  public int SetInheritAlpha(CigiBaseEntityCtrl.InheritAlphaGrp InheritAlphaIn, bool bndchk) {
    int ret = ccl_dllDPINVOKE.CigiEntityCtrlV3_SetInheritAlpha__SWIG_0(swigCPtr, (int)InheritAlphaIn, bndchk);
    return ret;
  }

  public int SetInheritAlpha(CigiBaseEntityCtrl.InheritAlphaGrp InheritAlphaIn) {
    int ret = ccl_dllDPINVOKE.CigiEntityCtrlV3_SetInheritAlpha__SWIG_1(swigCPtr, (int)InheritAlphaIn);
    return ret;
  }

  public CigiBaseEntityCtrl.InheritAlphaGrp GetInheritAlpha() {
    CigiBaseEntityCtrl.InheritAlphaGrp ret = (CigiBaseEntityCtrl.InheritAlphaGrp)ccl_dllDPINVOKE.CigiEntityCtrlV3_GetInheritAlpha(swigCPtr);
    return ret;
  }

  public int SetAnimationDir(CigiBaseEntityCtrl.AnimationDirGrp AnimationDirIn, bool bndchk) {
    int ret = ccl_dllDPINVOKE.CigiEntityCtrlV3_SetAnimationDir__SWIG_0(swigCPtr, (int)AnimationDirIn, bndchk);
    return ret;
  }

  public int SetAnimationDir(CigiBaseEntityCtrl.AnimationDirGrp AnimationDirIn) {
    int ret = ccl_dllDPINVOKE.CigiEntityCtrlV3_SetAnimationDir__SWIG_1(swigCPtr, (int)AnimationDirIn);
    return ret;
  }

  public CigiBaseEntityCtrl.AnimationDirGrp GetAnimationDir() {
    CigiBaseEntityCtrl.AnimationDirGrp ret = (CigiBaseEntityCtrl.AnimationDirGrp)ccl_dllDPINVOKE.CigiEntityCtrlV3_GetAnimationDir(swigCPtr);
    return ret;
  }

  public int SetAnimationLoopMode(CigiBaseEntityCtrl.AnimationLoopModeGrp AnimationLoopModeIn, bool bndchk) {
    int ret = ccl_dllDPINVOKE.CigiEntityCtrlV3_SetAnimationLoopMode__SWIG_0(swigCPtr, (int)AnimationLoopModeIn, bndchk);
    return ret;
  }

  public int SetAnimationLoopMode(CigiBaseEntityCtrl.AnimationLoopModeGrp AnimationLoopModeIn) {
    int ret = ccl_dllDPINVOKE.CigiEntityCtrlV3_SetAnimationLoopMode__SWIG_1(swigCPtr, (int)AnimationLoopModeIn);
    return ret;
  }

  public CigiBaseEntityCtrl.AnimationLoopModeGrp GetAnimationLoopMode() {
    CigiBaseEntityCtrl.AnimationLoopModeGrp ret = (CigiBaseEntityCtrl.AnimationLoopModeGrp)ccl_dllDPINVOKE.CigiEntityCtrlV3_GetAnimationLoopMode(swigCPtr);
    return ret;
  }

  public int SetAnimationState(CigiBaseEntityCtrl.AnimationStateGrp AnimationStateIn, bool bndchk) {
    int ret = ccl_dllDPINVOKE.CigiEntityCtrlV3_SetAnimationState__SWIG_0(swigCPtr, (int)AnimationStateIn, bndchk);
    return ret;
  }

  public int SetAnimationState(CigiBaseEntityCtrl.AnimationStateGrp AnimationStateIn) {
    int ret = ccl_dllDPINVOKE.CigiEntityCtrlV3_SetAnimationState__SWIG_1(swigCPtr, (int)AnimationStateIn);
    return ret;
  }

  public CigiBaseEntityCtrl.AnimationStateGrp GetAnimationState() {
    CigiBaseEntityCtrl.AnimationStateGrp ret = (CigiBaseEntityCtrl.AnimationStateGrp)ccl_dllDPINVOKE.CigiEntityCtrlV3_GetAnimationState(swigCPtr);
    return ret;
  }

}
