//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class CigiBaseMaritimeSurfaceCtrl : CigiBasePacket {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal CigiBaseMaritimeSurfaceCtrl(global::System.IntPtr cPtr, bool cMemoryOwn) : base(ccl_dllDPINVOKE.CigiBaseMaritimeSurfaceCtrl_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CigiBaseMaritimeSurfaceCtrl obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CigiBaseMaritimeSurfaceCtrl obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ccl_dllDPINVOKE.delete_CigiBaseMaritimeSurfaceCtrl(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public override int Pack(CigiBasePacket Base, SWIGTYPE_p_unsigned___int8 Buff, SWIGTYPE_p_void Spec) {
    int ret = ccl_dllDPINVOKE.CigiBaseMaritimeSurfaceCtrl_Pack(swigCPtr, CigiBasePacket.getCPtr(Base), SWIGTYPE_p_unsigned___int8.getCPtr(Buff), SWIGTYPE_p_void.getCPtr(Spec));
    return ret;
  }

  public override int Unpack(SWIGTYPE_p_unsigned___int8 Buff, bool Swap, SWIGTYPE_p_void Spec) {
    int ret = ccl_dllDPINVOKE.CigiBaseMaritimeSurfaceCtrl_Unpack(swigCPtr, SWIGTYPE_p_unsigned___int8.getCPtr(Buff), Swap, SWIGTYPE_p_void.getCPtr(Spec));
    return ret;
  }

  public override int GetCnvt(CigiVersionID CnvtVersion, SWIGTYPE_p_CigiCnvtInfoType__Type CnvtInfo) {
    int ret = ccl_dllDPINVOKE.CigiBaseMaritimeSurfaceCtrl_GetCnvt(swigCPtr, CigiVersionID.getCPtr(CnvtVersion), SWIGTYPE_p_CigiCnvtInfoType__Type.getCPtr(CnvtInfo));
    if (ccl_dllDPINVOKE.SWIGPendingException.Pending) throw ccl_dllDPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int SetEntityRgnID(SWIGTYPE_p_unsigned___int16 EntityRgnIDIn, bool bndchk) {
    int ret = ccl_dllDPINVOKE.CigiBaseMaritimeSurfaceCtrl_SetEntityRgnID__SWIG_0(swigCPtr, SWIGTYPE_p_unsigned___int16.getCPtr(EntityRgnIDIn), bndchk);
    if (ccl_dllDPINVOKE.SWIGPendingException.Pending) throw ccl_dllDPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int SetEntityRgnID(SWIGTYPE_p_unsigned___int16 EntityRgnIDIn) {
    int ret = ccl_dllDPINVOKE.CigiBaseMaritimeSurfaceCtrl_SetEntityRgnID__SWIG_1(swigCPtr, SWIGTYPE_p_unsigned___int16.getCPtr(EntityRgnIDIn));
    if (ccl_dllDPINVOKE.SWIGPendingException.Pending) throw ccl_dllDPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_unsigned___int16 GetEntityRgnID() {
    SWIGTYPE_p_unsigned___int16 ret = new SWIGTYPE_p_unsigned___int16(ccl_dllDPINVOKE.CigiBaseMaritimeSurfaceCtrl_GetEntityRgnID(swigCPtr), true);
    return ret;
  }

  public int SetSurfaceCondEn(bool SurfaceCondEnIn, bool bndchk) {
    int ret = ccl_dllDPINVOKE.CigiBaseMaritimeSurfaceCtrl_SetSurfaceCondEn__SWIG_0(swigCPtr, SurfaceCondEnIn, bndchk);
    return ret;
  }

  public int SetSurfaceCondEn(bool SurfaceCondEnIn) {
    int ret = ccl_dllDPINVOKE.CigiBaseMaritimeSurfaceCtrl_SetSurfaceCondEn__SWIG_1(swigCPtr, SurfaceCondEnIn);
    return ret;
  }

  public bool GetSurfaceCondEn() {
    bool ret = ccl_dllDPINVOKE.CigiBaseMaritimeSurfaceCtrl_GetSurfaceCondEn(swigCPtr);
    return ret;
  }

  public int SetWhitecapEn(bool WhitecapEnIn, bool bndchk) {
    int ret = ccl_dllDPINVOKE.CigiBaseMaritimeSurfaceCtrl_SetWhitecapEn__SWIG_0(swigCPtr, WhitecapEnIn, bndchk);
    return ret;
  }

  public int SetWhitecapEn(bool WhitecapEnIn) {
    int ret = ccl_dllDPINVOKE.CigiBaseMaritimeSurfaceCtrl_SetWhitecapEn__SWIG_1(swigCPtr, WhitecapEnIn);
    return ret;
  }

  public bool GetWhitecapEn() {
    bool ret = ccl_dllDPINVOKE.CigiBaseMaritimeSurfaceCtrl_GetWhitecapEn(swigCPtr);
    return ret;
  }

  public int SetScope(CigiBaseMaritimeSurfaceCtrl.ScopeGrp ScopeIn, bool bndchk) {
    int ret = ccl_dllDPINVOKE.CigiBaseMaritimeSurfaceCtrl_SetScope__SWIG_0(swigCPtr, (int)ScopeIn, bndchk);
    return ret;
  }

  public int SetScope(CigiBaseMaritimeSurfaceCtrl.ScopeGrp ScopeIn) {
    int ret = ccl_dllDPINVOKE.CigiBaseMaritimeSurfaceCtrl_SetScope__SWIG_1(swigCPtr, (int)ScopeIn);
    return ret;
  }

  public CigiBaseMaritimeSurfaceCtrl.ScopeGrp GetScope() {
    CigiBaseMaritimeSurfaceCtrl.ScopeGrp ret = (CigiBaseMaritimeSurfaceCtrl.ScopeGrp)ccl_dllDPINVOKE.CigiBaseMaritimeSurfaceCtrl_GetScope(swigCPtr);
    return ret;
  }

  public int SetSurfaceHeight(float SurfaceHeightIn, bool bndchk) {
    int ret = ccl_dllDPINVOKE.CigiBaseMaritimeSurfaceCtrl_SetSurfaceHeight__SWIG_0(swigCPtr, SurfaceHeightIn, bndchk);
    return ret;
  }

  public int SetSurfaceHeight(float SurfaceHeightIn) {
    int ret = ccl_dllDPINVOKE.CigiBaseMaritimeSurfaceCtrl_SetSurfaceHeight__SWIG_1(swigCPtr, SurfaceHeightIn);
    return ret;
  }

  public float GetSurfaceHeight() {
    float ret = ccl_dllDPINVOKE.CigiBaseMaritimeSurfaceCtrl_GetSurfaceHeight(swigCPtr);
    return ret;
  }

  public int SetWaterTemp(float WaterTempIn, bool bndchk) {
    int ret = ccl_dllDPINVOKE.CigiBaseMaritimeSurfaceCtrl_SetWaterTemp__SWIG_0(swigCPtr, WaterTempIn, bndchk);
    return ret;
  }

  public int SetWaterTemp(float WaterTempIn) {
    int ret = ccl_dllDPINVOKE.CigiBaseMaritimeSurfaceCtrl_SetWaterTemp__SWIG_1(swigCPtr, WaterTempIn);
    return ret;
  }

  public float GetWaterTemp() {
    float ret = ccl_dllDPINVOKE.CigiBaseMaritimeSurfaceCtrl_GetWaterTemp(swigCPtr);
    return ret;
  }

  public int SetClarity(float ClarityIn, bool bndchk) {
    int ret = ccl_dllDPINVOKE.CigiBaseMaritimeSurfaceCtrl_SetClarity__SWIG_0(swigCPtr, ClarityIn, bndchk);
    return ret;
  }

  public int SetClarity(float ClarityIn) {
    int ret = ccl_dllDPINVOKE.CigiBaseMaritimeSurfaceCtrl_SetClarity__SWIG_1(swigCPtr, ClarityIn);
    return ret;
  }

  public float GetClarity() {
    float ret = ccl_dllDPINVOKE.CigiBaseMaritimeSurfaceCtrl_GetClarity(swigCPtr);
    return ret;
  }

  public enum ScopeGrp {
    Global = 0,
    Regional = 1,
    Entity = 2
  }

}
