//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class CigiBasePositionReq : CigiBasePacket {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal CigiBasePositionReq(global::System.IntPtr cPtr, bool cMemoryOwn) : base(example_modulePINVOKE.CigiBasePositionReq_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CigiBasePositionReq obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CigiBasePositionReq obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          example_modulePINVOKE.delete_CigiBasePositionReq(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public override int Pack(CigiBasePacket Base, SWIGTYPE_p_unsigned___int8 Buff, SWIGTYPE_p_void Spec) {
    int ret = example_modulePINVOKE.CigiBasePositionReq_Pack(swigCPtr, CigiBasePacket.getCPtr(Base), SWIGTYPE_p_unsigned___int8.getCPtr(Buff), SWIGTYPE_p_void.getCPtr(Spec));
    return ret;
  }

  public override int Unpack(SWIGTYPE_p_unsigned___int8 Buff, bool Swap, SWIGTYPE_p_void Spec) {
    int ret = example_modulePINVOKE.CigiBasePositionReq_Unpack(swigCPtr, SWIGTYPE_p_unsigned___int8.getCPtr(Buff), Swap, SWIGTYPE_p_void.getCPtr(Spec));
    return ret;
  }

  public override int GetCnvt(CigiVersionID CnvtVersion, SWIGTYPE_p_CigiCnvtInfoType__Type CnvtInfo) {
    int ret = example_modulePINVOKE.CigiBasePositionReq_GetCnvt(swigCPtr, CigiVersionID.getCPtr(CnvtVersion), SWIGTYPE_p_CigiCnvtInfoType__Type.getCPtr(CnvtInfo));
    if (example_modulePINVOKE.SWIGPendingException.Pending) throw example_modulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int SetObjectID(SWIGTYPE_p_unsigned___int16 ObjectIDIn, bool bndchk) {
    int ret = example_modulePINVOKE.CigiBasePositionReq_SetObjectID__SWIG_0(swigCPtr, SWIGTYPE_p_unsigned___int16.getCPtr(ObjectIDIn), bndchk);
    if (example_modulePINVOKE.SWIGPendingException.Pending) throw example_modulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int SetObjectID(SWIGTYPE_p_unsigned___int16 ObjectIDIn) {
    int ret = example_modulePINVOKE.CigiBasePositionReq_SetObjectID__SWIG_1(swigCPtr, SWIGTYPE_p_unsigned___int16.getCPtr(ObjectIDIn));
    if (example_modulePINVOKE.SWIGPendingException.Pending) throw example_modulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_unsigned___int16 GetObjectID() {
    SWIGTYPE_p_unsigned___int16 ret = new SWIGTYPE_p_unsigned___int16(example_modulePINVOKE.CigiBasePositionReq_GetObjectID(swigCPtr), true);
    return ret;
  }

  public int SetArtPartID(SWIGTYPE_p_unsigned___int8 ArtPartIDIn, bool bndchk) {
    int ret = example_modulePINVOKE.CigiBasePositionReq_SetArtPartID__SWIG_0(swigCPtr, SWIGTYPE_p_unsigned___int8.getCPtr(ArtPartIDIn), bndchk);
    if (example_modulePINVOKE.SWIGPendingException.Pending) throw example_modulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int SetArtPartID(SWIGTYPE_p_unsigned___int8 ArtPartIDIn) {
    int ret = example_modulePINVOKE.CigiBasePositionReq_SetArtPartID__SWIG_1(swigCPtr, SWIGTYPE_p_unsigned___int8.getCPtr(ArtPartIDIn));
    if (example_modulePINVOKE.SWIGPendingException.Pending) throw example_modulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_unsigned___int8 GetArtPartID() {
    SWIGTYPE_p_unsigned___int8 ret = new SWIGTYPE_p_unsigned___int8(example_modulePINVOKE.CigiBasePositionReq_GetArtPartID(swigCPtr), true);
    return ret;
  }

  public int SetUpdateMode(CigiBasePositionReq.UpdateModeGrp UpdateModeIn, bool bndchk) {
    int ret = example_modulePINVOKE.CigiBasePositionReq_SetUpdateMode__SWIG_0(swigCPtr, (int)UpdateModeIn, bndchk);
    return ret;
  }

  public int SetUpdateMode(CigiBasePositionReq.UpdateModeGrp UpdateModeIn) {
    int ret = example_modulePINVOKE.CigiBasePositionReq_SetUpdateMode__SWIG_1(swigCPtr, (int)UpdateModeIn);
    return ret;
  }

  public CigiBasePositionReq.UpdateModeGrp GetUpdateMode() {
    CigiBasePositionReq.UpdateModeGrp ret = (CigiBasePositionReq.UpdateModeGrp)example_modulePINVOKE.CigiBasePositionReq_GetUpdateMode(swigCPtr);
    return ret;
  }

  public int SetObjectClass(CigiBasePositionReq.ObjectClassGrp ObjectClassIn, bool bndchk) {
    int ret = example_modulePINVOKE.CigiBasePositionReq_SetObjectClass__SWIG_0(swigCPtr, (int)ObjectClassIn, bndchk);
    return ret;
  }

  public int SetObjectClass(CigiBasePositionReq.ObjectClassGrp ObjectClassIn) {
    int ret = example_modulePINVOKE.CigiBasePositionReq_SetObjectClass__SWIG_1(swigCPtr, (int)ObjectClassIn);
    return ret;
  }

  public CigiBasePositionReq.ObjectClassGrp GetObjectClass() {
    CigiBasePositionReq.ObjectClassGrp ret = (CigiBasePositionReq.ObjectClassGrp)example_modulePINVOKE.CigiBasePositionReq_GetObjectClass(swigCPtr);
    return ret;
  }

  public int SetCoordSys(CigiBasePositionReq.CoordSysGrp CoordSysIn, bool bndchk) {
    int ret = example_modulePINVOKE.CigiBasePositionReq_SetCoordSys__SWIG_0(swigCPtr, (int)CoordSysIn, bndchk);
    return ret;
  }

  public int SetCoordSys(CigiBasePositionReq.CoordSysGrp CoordSysIn) {
    int ret = example_modulePINVOKE.CigiBasePositionReq_SetCoordSys__SWIG_1(swigCPtr, (int)CoordSysIn);
    return ret;
  }

  public CigiBasePositionReq.CoordSysGrp GetCoordSys() {
    CigiBasePositionReq.CoordSysGrp ret = (CigiBasePositionReq.CoordSysGrp)example_modulePINVOKE.CigiBasePositionReq_GetCoordSys(swigCPtr);
    return ret;
  }

  public enum UpdateModeGrp {
    OneShot = 0,
    Continuous = 1
  }

  public enum ObjectClassGrp {
    Entity = 0,
    ArtPart = 1,
    View = 2,
    ViewGrp = 3,
    MotionTracker = 4
  }

  public enum CoordSysGrp {
    Geodetic = 0,
    ParentEntity = 1,
    Submodel = 2
  }

}
