//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class CigiBaseHatHotReq : CigiBasePacket {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal CigiBaseHatHotReq(global::System.IntPtr cPtr, bool cMemoryOwn) : base(example_modulePINVOKE.CigiBaseHatHotReq_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CigiBaseHatHotReq obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CigiBaseHatHotReq obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          example_modulePINVOKE.delete_CigiBaseHatHotReq(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public override int Pack(CigiBasePacket Base, SWIGTYPE_p_unsigned___int8 Buff, SWIGTYPE_p_void Spec) {
    int ret = example_modulePINVOKE.CigiBaseHatHotReq_Pack(swigCPtr, CigiBasePacket.getCPtr(Base), SWIGTYPE_p_unsigned___int8.getCPtr(Buff), SWIGTYPE_p_void.getCPtr(Spec));
    return ret;
  }

  public override int Unpack(SWIGTYPE_p_unsigned___int8 Buff, bool Swap, SWIGTYPE_p_void Spec) {
    int ret = example_modulePINVOKE.CigiBaseHatHotReq_Unpack(swigCPtr, SWIGTYPE_p_unsigned___int8.getCPtr(Buff), Swap, SWIGTYPE_p_void.getCPtr(Spec));
    return ret;
  }

  public int SetHatHotID(SWIGTYPE_p_unsigned___int16 HatHotIDIn, bool bndchk) {
    int ret = example_modulePINVOKE.CigiBaseHatHotReq_SetHatHotID__SWIG_0(swigCPtr, SWIGTYPE_p_unsigned___int16.getCPtr(HatHotIDIn), bndchk);
    if (example_modulePINVOKE.SWIGPendingException.Pending) throw example_modulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int SetHatHotID(SWIGTYPE_p_unsigned___int16 HatHotIDIn) {
    int ret = example_modulePINVOKE.CigiBaseHatHotReq_SetHatHotID__SWIG_1(swigCPtr, SWIGTYPE_p_unsigned___int16.getCPtr(HatHotIDIn));
    if (example_modulePINVOKE.SWIGPendingException.Pending) throw example_modulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_unsigned___int16 GetHatHotID() {
    SWIGTYPE_p_unsigned___int16 ret = new SWIGTYPE_p_unsigned___int16(example_modulePINVOKE.CigiBaseHatHotReq_GetHatHotID(swigCPtr), true);
    return ret;
  }

  public int SetLat(double LatIn, bool bndchk) {
    int ret = example_modulePINVOKE.CigiBaseHatHotReq_SetLat__SWIG_0(swigCPtr, LatIn, bndchk);
    return ret;
  }

  public int SetLat(double LatIn) {
    int ret = example_modulePINVOKE.CigiBaseHatHotReq_SetLat__SWIG_1(swigCPtr, LatIn);
    return ret;
  }

  public double GetLat() {
    double ret = example_modulePINVOKE.CigiBaseHatHotReq_GetLat(swigCPtr);
    return ret;
  }

  public int SetLon(double LonIn, bool bndchk) {
    int ret = example_modulePINVOKE.CigiBaseHatHotReq_SetLon__SWIG_0(swigCPtr, LonIn, bndchk);
    return ret;
  }

  public int SetLon(double LonIn) {
    int ret = example_modulePINVOKE.CigiBaseHatHotReq_SetLon__SWIG_1(swigCPtr, LonIn);
    return ret;
  }

  public double GetLon() {
    double ret = example_modulePINVOKE.CigiBaseHatHotReq_GetLon(swigCPtr);
    return ret;
  }

  public enum ReqTypeGrp {
    HAT = 0,
    HOT = 1,
    Extended = 2
  }

  public enum CoordSysGrp {
    Geodetic = 0,
    Entity = 1
  }

}
